-i ${COMMON_CELLS_DIR}/include

${CV32E40P_DIR}/bhv/cv32e40p_sim_clock_gate.sv
${CV32E40P_DIR}/rtl/cv32e40p_sleep_unit.sv
${CV32E40P_DIR}/rtl/cv32e40p_prefetch_controller.sv
${CV32E40P_DIR}/rtl/cv32e40p_fifo.sv
${CV32E40P_DIR}/rtl/cv32e40p_obi_interface.sv
${CV32E40P_DIR}/rtl/cv32e40p_prefetch_buffer.sv
${CV32E40P_DIR}/rtl/cv32e40p_aligner.sv
${CV32E40P_DIR}/rtl/cv32e40p_compressed_decoder.sv
${CV32E40P_DIR}/rtl/cv32e40p_if_stage.sv
${CV32E40P_DIR}/rtl/cv32e40p_register_file_ff.sv
${CV32E40P_DIR}/rtl/cv32e40p_decoder.sv
${CV32E40P_DIR}/rtl/cv32e40p_controller.sv
${CV32E40P_DIR}/rtl/cv32e40p_int_controller.sv
${CV32E40P_DIR}/rtl/cv32e40p_id_stage.sv
${CV32E40P_DIR}/rtl/cv32e40p_popcnt.sv
${CV32E40P_DIR}/rtl/cv32e40p_ff_one.sv
${CV32E40P_DIR}/rtl/cv32e40p_alu_div.sv
${CV32E40P_DIR}/rtl/cv32e40p_alu.sv
${CV32E40P_DIR}/rtl/cv32e40p_mult.sv
${CV32E40P_DIR}/rtl/cv32e40p_apu_disp.sv
${CV32E40P_DIR}/rtl/cv32e40p_ex_stage.sv
${CV32E40P_DIR}/rtl/cv32e40p_cs_registers.sv
${CV32E40P_DIR}/rtl/cv32e40p_core.sv
${CVFPU_DIR}/src/fpnew_classifier.sv
${COMMON_CELLS_DIR}/src/lzc.sv
${CVFPU_DIR}/src/fpnew_rounding.sv
${CVFPU_DIR}/src/fpnew_fma_multi.sv
${CVFPU_DIR}/src/fpnew_opgroup_multifmt_slice.sv
${COMMON_CELLS_DIR}/src/rr_arb_tree.sv
${CVFPU_DIR}/src/fpnew_opgroup_block.sv
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
${CVFPU_DIR}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
${CVFPU_DIR}/src/fpnew_divsqrt_th_32.sv
${CVFPU_DIR}/src/fpnew_noncomp.sv
${CVFPU_DIR}/src/fpnew_opgroup_fmt_slice.sv
${CVFPU_DIR}/src/fpnew_cast_multi.sv
${CVFPU_DIR}/src/fpnew_top.sv
${DUAL_HELIX_SOC_DIR}/hardware/source/cv32e40p/cv32e40p_fp_wrapper.sv
${CV32E40P_DIR}/rtl/cv32e40p_top.sv
${CVFPU_DIR}/src/fpnew_divsqrt_th_64_multi.sv
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
${CVFPU_DIR}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
${DUAL_HELIX_SOC_DIR}/hardware/source/cv32e40p/cv32e40p_load_store_unit.sv
